### ISSUE TITLE
Can we get the Modal code to port this to Replicate?

### ISSUE THREAD

**Issue by zsxkib** [whitead/minimalaf#1]
Hey there!

Your minimal AlphaFold setup looks super cool. We'd love to get this running on Replicate too.

Mind sharing the full Modal code? We're especially after:

1. Any extra files not on GitHub
2. Modal-specific config stuff
3. Deployment scripts (if you've got 'em)

The idea is to keep it as simple as your Modal version, just on Replicate instead.

Thanks a bunch! Let us know if you've got any questions or want to chat about it.

Cheers!

**Comment by whitead** [comment]
The modal code is in the repo - `af.py`: https://github.com/whitead/minimalaf/blob/main/af.py
